### PR TITLE
First round of Swift 1.2 updates.

### PR DESCRIPTION
**Pull request by kreeger**
Figured you folks might want a little hand on this, and I'm happy to help!

This is an initial round of changes to get the project to comply with the latest Swift 1.2 compiler changes. App runs, tests pass, things look pretty hunky-dory. Let me know if you have any questions!

### CODE REVIEW

**Comment by nwinter** [comment]
Wow, thanks @kreeger! Are you at all interested in helping out more with the iPad app? We haven't been able to get it running quickly on all but the newest iPad Airs, so we haven't been able to release it, but I wonder if you have any ideas for speeding things up (or even just want to do some performance testing on whatever devices you might have). What do you think?

**Comment by nwinter** [comment]
Also, can you [sign the CLA](http://codecombat.com/cla)? (It's easy.)

**Comment by kreeger** [comment]
@nwinter I'd love to help! I'll take a look at the CLA this evening. I've got an old iPad 3rd-gen, so I've got a pretty good baseline to test against. I'll see what I can do!

**Comment by kreeger** [comment]
@nwinter is there an open issue on the performance problems? I've got some possible input to note (I'd like to put it somewhere relevant).

**Comment by nwinter** [comment]
Sure; I just opened https://github.com/codecombat/codecombat-ios/issues/38 and https://github.com/codecombat/codecombat-ios/issues/39 to talk about performance issues.

**Pull request merged**
